
model_path: 'models/mnist_net.pth'
#model_path: 'models/cifar_net.pth'
#model_path: 'models/cifar_net_resnet.pth'

# trigger_path: '/app/trigger/trigger_10.png' 
trigger_path: 'trigger/trigger_10.png' 
hf_model_folder_path: 'models/hf_model'